mavros:
  ros__parameters:
    plugin_blacklist: []
    plugin_whitelist:
      - 'actuator_control'
      - 'adcs'
      - 'adsb'
      - 'altitude'
      - 'cam_imu_sync'
      - 'camera'
      - 'cellular_status'
      - 'command'
      - 'companion_process_status'
      - 'debug_value'
      - 'distance_sensor'
      - 'esc_status'
      - 'esc_telemetry'
      - 'fake_gps'
      - 'ftp'
      - 'global_position'
      - 'gps_rtk'
      - 'gps_status'
      - 'hil'
      - 'home_position'
      - 'imu'
      - 'landing_target'
      - 'local_position'
      - 'log_transfer'
      - 'manual_control'
      - 'mission'
      - 'mocap_pose_estimate'
      - 'mount_control'
      - 'obstacle_distance'
      - 'odometry'
      - 'param'
      - 'play_tune_v2'
      - 'px4flow'
      - 'rangefinder'
      - 'rc_io'
      - 'safety_area'
      - 'setpoint_accel'
      - 'setpoint_attitude'
      - 'setpoint_position'
      - 'setpoint_raw'
      - 'setpoint_trajectory'
      - 'setpoint_velocity'
      - 'sys_status'
      - 'sys_time'
      - 'telemetry_status'
      - 'time_sync'
      - 'trajectory'
      - 'vibration'
      - 'vision_pose_estimate'
      - 'vision_speed_estimate'
      - 'waypoint'
